### PR TITLE
Change cobertura plugin with jacoco plugin.

### PR DESCRIPTION
**Pull request by javadev**
It works faster and has better support for JAVA SE 8.

### CODE REVIEW

**Comment by OleksandrPavloshchuk** [comment]
"Change cobertura plugin with jacoco plugin. …
It works faster and has better support for JAVA SE 8."
Thank you for this piece of advice. I'll add it to the issues.

I've started this task in order do help my daughter in development web application project for interactive rendering of some complex plane sets. I want to allow "deep diving" into plane areas with the most possible precision. I've discovered, that usual double type does not satisfy me, so I suppose, that BigDecimal also has some restrictions. Now I'm working around correct division support.

**Comment by OleksandrPavloshchuk** [comment]
It's interesting to face with problems of processing the REALLY big numbers. :) Is the multithreading necessary for it, and how to invoke it correctly?

**Comment by javadev** [comment]
Good. To apply this changes you may merge this pull request :)

**Comment by javadev** [comment]
Multithreading should work out of the box in java :)

**Pull request merged**
